#!/usr/bin/env python3
"""The UI dimension table, generated from the CEG namespace registry.

    python3 client/tools/gen_dimension_table.py --write       # regenerate Dimensions.kt
    python3 client/tools/gen_dimension_table.py --check       # fail if stale / unresolvable
    python3 client/tools/gen_dimension_table.py --self-test   # prove --check goes red

THE IDEA (design handoff, "The namespace is the design system"). The 116 CEG
families in CIRISConstitution's `namespace_registry.json` each carry a
polarity, and polarity is a render instruction. So the UI table is a JOIN onto
the registry — family -> renderer class, label key, gloss key — generated,
never hand-written. A card names `Dim.consentKind`; a family with no registry
row cannot be named, so it cannot be rendered (CC 3.1.7 R2: on the wire an
unregistered family already admits under an authority nobody chose).

INPUTS (all under client/ceg/):
  namespace_registry.json   vendored, pinned — see client/ceg/README.md
  glosses.json              plain-English label + gloss per family the UI touches
  renderers.json            renderer overrides by prefix, on top of the polarity default

OUTPUT: shared/src/commonMain/kotlin/ai/ciris/mobile/shared/ceg/Dimensions.kt

WHAT --check REFUSES: a stale output; a registry whose sha differs from the
constant in the output; a gloss key that is not a registry prefix or an
envelope member; a renderer override for a prefix that does not exist or that
contradicts the family's polarity; an emitted localization key that does not
resolve in the canonical en.json (the localization gate only checks literal
`localizedString("…")` calls, so the generated keys are checked here).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import shutil
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
CEG = ROOT / "ceg"
REGISTRY = CEG / "namespace_registry.json"
GLOSSES = CEG / "glosses.json"
RENDERERS = CEG / "renderers.json"
EN_JSON = ROOT / "shared" / "src" / "desktopMain" / "resources" / "localization" / "en.json"
TARGET = (ROOT / "shared" / "src" / "commonMain" / "kotlin" / "ai" / "ciris" / "mobile"
          / "shared" / "ceg" / "Dimensions.kt")

POLARITY = {
    "signed": ("SIGNED", False),
    "boolean-via-score": ("BOOLEAN_VIA_SCORE", False),
    "boolean-via-score; Indeterminate allowed → RESTRICTED": ("BOOLEAN_VIA_SCORE", True),
    "positive-only": ("POSITIVE_ONLY", False),
    "enumerated": ("ENUMERATED", False),
    "-1 only": ("MINUS_ONE_ONLY", False),
    "-1 / -0.5 only": ("MINUS_ONE_OR_HALF", False),
    "per-leaf (CC 3.3.1)": ("PER_LEAF", False),
    "see CC 3.4.1": ("BY_RULE", False),
}

RENDERERS_ALL = [
    "SIGNED_SCORE", "BOOLEAN_VIA_SCORE", "POSITIVE_ONLY_ACCRUAL", "VIOLATION_MARKER",
    "ENUMERATED_CHIP", "STATE_PILL", "CONTENT_REFERENCE", "RELATION_EDGE",
    "CONFIG_RECORD", "CONSENT_LEAF", "SETTLEMENT_RECEIPT",
]
MINUS = {"MINUS_ONE_ONLY", "MINUS_ONE_OR_HALF"}

# The CC 2.1 envelope members the receipt renders. Not registry rows; the
# CSD convention for them is `x_private:<member>` (CSD-004).
ENVELOPE = [
    ("subjectKeyIds", "subject_key_ids", "2.1"),
    ("attestingKeyId", "attesting_key_id", "2.1"),
    ("cohortScope", "cohort_scope", "2.3.3"),
    ("dimension", "dimension", "2.1"),
    ("consentScope", "consent:scope", "3.3.1"),
]

SEG_CLASS = {"literal": "LITERAL", "vocab": "VOCAB", "value": "VALUE",
             "wildcard": "WILDCARD", "external": "EXTERNAL", "hex": "HEX"}

HEADER = """// GENERATED by client/tools/gen_dimension_table.py — do not edit.
// Inputs: client/ceg/namespace_registry.json (pinned), glosses.json, renderers.json.
// Re-run `python3 client/tools/gen_dimension_table.py --write` after changing any of them.
package ai.ciris.mobile.shared.ceg

"""


class Refusal(Exception):
    pass


def kotlin_name(prefix: str) -> str:
    parts = [p for p in prefix.split(":") if p != "*"]
    words = []
    for p in parts:
        p = p.strip("{}")
        words.extend(w for w in re.split(r"[^A-Za-z0-9]+", p) if w)
    if not words:
        raise Refusal(f"cannot name {prefix!r}")
    name = words[0].lower() + "".join(w[:1].upper() + w[1:].lower() for w in words[1:])
    if name[0].isdigit():
        name = "d" + name
    return name


def slug(prefix: str) -> str:
    parts = ["any" if p == "*" else p.strip("{}") for p in prefix.split(":")]
    return re.sub(r"[^a-z0-9]+", "_", ":".join(parts).lower()).strip("_")


def kstr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", " ") + '"'


def resolve_key(en: dict, key: str) -> bool:
    node = en
    for part in key.split("."):
        if not isinstance(node, dict) or part not in node:
            return False
        node = node[part]
    return isinstance(node, str)


def build(registry_path: pathlib.Path, glosses_path: pathlib.Path, renderers_path: pathlib.Path,
          en_path: pathlib.Path) -> str:
    reg = json.loads(registry_path.read_text(encoding="utf-8"))
    families = reg.get("families") or []
    if not families:
        raise Refusal(f"{registry_path}: no families — empty registry or changed shape")
    meta = reg["_meta"]
    glosses = {k: v for k, v in json.loads(glosses_path.read_text(encoding="utf-8")).items() if not k.startswith("_")}
    renderers_doc = json.loads(renderers_path.read_text(encoding="utf-8"))
    overrides = {k: v for k, v in renderers_doc.items() if not k.startswith("_")}
    default_by_polarity = renderers_doc["_meta"]["default_by_polarity"]
    rule_overrides = renderers_doc["_meta"].get("rule_overrides", {})
    en = json.loads(en_path.read_text(encoding="utf-8"))

    prefixes = {f["prefix"] for f in families}
    envelope_keys = {f"envelope:{wire}" for _, wire, _ in ENVELOPE}
    for k in glosses:
        if k not in prefixes and k not in envelope_keys:
            raise Refusal(f"glosses.json names {k!r}, which is neither a registry prefix nor an envelope member")
    for k, r in overrides.items():
        if k not in prefixes:
            raise Refusal(f"renderers.json overrides {k!r}, which is not a registry prefix")
        if r not in RENDERERS_ALL:
            raise Refusal(f"renderers.json: unknown renderer {r!r} for {k!r}")

    rows = []
    names = set()
    slugs = set()
    missing_gloss = []
    for f in sorted(families, key=lambda f: f["prefix"]):
        prefix = f["prefix"]
        raw = f["polarity"]
        if raw not in POLARITY:
            raise Refusal(f"{prefix}: unknown polarity {raw!r} — extend POLARITY deliberately")
        pol, indeterminate = POLARITY[raw]
        rule = (f.get("reserved_rule") or {}).get("rule")
        renderer = default_by_polarity[pol]
        if rule in rule_overrides:
            renderer = rule_overrides[rule]
        if prefix in overrides:
            renderer = overrides[prefix]
        # polarity is a visual rule — an override may not contradict it
        if pol in MINUS and renderer != "VIOLATION_MARKER":
            raise Refusal(f"{prefix}: polarity {raw!r} can only render as VIOLATION_MARKER, not {renderer}")
        if renderer == "VIOLATION_MARKER" and pol not in MINUS:
            raise Refusal(f"{prefix}: VIOLATION_MARKER is for minus-only families; polarity is {raw!r}")
        if pol == "POSITIVE_ONLY" and renderer == "SIGNED_SCORE":
            raise Refusal(f"{prefix}: a positive-only family is never a signed score")
        name = kotlin_name(prefix)
        if name in names:
            raise Refusal(f"Kotlin name collision: {name} ({prefix})")
        names.add(name)
        sl = slug(prefix)
        if sl in slugs:
            raise Refusal(f"slug collision: {sl} ({prefix})")
        slugs.add(sl)
        label_key = gloss_key = None
        if prefix in glosses:
            label_key, gloss_key = f"ceg.{sl}.label", f"ceg.{sl}.gloss"
            for k in (label_key, gloss_key):
                if not resolve_key(en, k):
                    raise Refusal(f"{prefix}: localization key {k} does not resolve in en.json")
        else:
            missing_gloss.append(prefix)
        segs = [(s["segment"], SEG_CLASS[s["class"]]) for s in f.get("segments", [])]
        if not segs:
            raise Refusal(f"{prefix}: no segments — registry predates rc5?")
        rows.append(dict(
            prefix=prefix, name=name, slug=sl, cc=f["cc_section"], pol=pol, raw=raw,
            indeterminate=indeterminate, renderer=renderer, component=f["owning_component"],
            reserved=bool(f.get("reserved")), rule=rule, segs=segs,
            label_key=label_key, gloss_key=gloss_key, description=f.get("description") or "",
        ))

    for _, wire, _ in ENVELOPE:
        k = f"envelope:{wire}"
        if k not in glosses:
            raise Refusal(f"glosses.json must gloss every envelope member; missing {k}")
        sl = "envelope." + re.sub(r"[^a-z0-9]+", "_", wire)
        for key in (f"ceg.{sl}.label", f"ceg.{sl}.gloss"):
            if not resolve_key(en, key):
                raise Refusal(f"{k}: localization key {key} does not resolve in en.json")

    file_sha = hashlib.sha256(registry_path.read_bytes()).hexdigest()

    out = [HEADER]
    out.append(f"const val REGISTRY_CC_VERSION = {kstr(meta['cc_version'])}\n")
    out.append(f"const val REGISTRY_FAMILY_COUNT = {len(rows)}\n")
    out.append("/** `_meta.source_sha256` — the CSD `registry_sha256:` convention (hash of the CC source). */\n")
    out.append(f"const val REGISTRY_SOURCE_SHA256 = {kstr(meta['source_sha256'])}\n")
    out.append("/** sha256 of client/ceg/namespace_registry.json itself; the currency gate compares this. */\n")
    out.append(f"const val REGISTRY_FILE_SHA256 = {kstr(file_sha)}\n\n")

    out.append("/** Every CEG family in the pinned registry, one `val` each. A screen names these; it never builds a Dimension. */\n")
    out.append("object Dim {\n")
    for r in rows:
        segs = ", ".join(f"Segment({kstr(s)}, SegmentClass.{c})" for s, c in r["segs"])
        out.append(
            f"    val {r['name']}: Dimension = Dimension(\n"
            f"        prefix = {kstr(r['prefix'])}, slug = {kstr(r['slug'])}, ccSection = {kstr(r['cc'])},\n"
            f"        polarity = Polarity.{r['pol']}, polarityRaw = {kstr(r['raw'])}, "
            f"indeterminateAllowed = {'true' if r['indeterminate'] else 'false'},\n"
            f"        renderer = Renderer.{r['renderer']}, owningComponent = {kstr(r['component'])}, "
            f"reserved = {'true' if r['reserved'] else 'false'}, reservedRule = {kstr(r['rule']) if r['rule'] else 'null'},\n"
            f"        segments = listOf({segs}),\n"
            f"        labelKey = {kstr(r['label_key']) if r['label_key'] else 'null'}, "
            f"glossKey = {kstr(r['gloss_key']) if r['gloss_key'] else 'null'},\n"
            f"        description = {kstr(r['description'])},\n"
            f"    )\n"
        )
    out.append("\n    val all: List<Dimension> = listOf(\n")
    for r in rows:
        out.append(f"        {r['name']},\n")
    out.append("    )\n\n")
    out.append("    private val byPrefixIndex: Map<String, Dimension> by lazy { all.associateBy { it.prefix } }\n\n")
    out.append("    /** The family whose registry prefix is exactly [prefix]. */\n")
    out.append("    fun byPrefix(prefix: String): Dimension? = byPrefixIndex[prefix]\n\n")
    out.append("    /**\n     * The family a wire `dimension` string belongs to: the row whose literal\n"
               "     * segments match the wire's leading segments, longest match wins.\n     */\n")
    out.append("    fun forWire(dimension: String): Dimension? {\n"
               "        val parts = dimension.split(':')\n"
               "        var best: Dimension? = null\n"
               "        var bestLen = -1\n"
               "        for (d in all) {\n"
               "            if (d.segments.size > parts.size) continue\n"
               "            var ok = true\n"
               "            var literals = 0\n"
               "            for ((i, seg) in d.segments.withIndex()) {\n"
               "                when (seg.cls) {\n"
               "                    SegmentClass.LITERAL -> if (seg.segment == parts[i]) literals++ else { ok = false; break }\n"
               "                    SegmentClass.WILDCARD -> {}\n"
               "                    else -> if (parts[i].isEmpty()) { ok = false; break }\n"
               "                }\n"
               "            }\n"
               "            if (ok && literals > bestLen) { best = d; bestLen = literals }\n"
               "        }\n"
               "        return best\n"
               "    }\n"
               "}\n\n")

    out.append("/** The CC 2.1 envelope members the receipt shows. Not registry rows; every one is glossed. */\n")
    out.append("object Envelope {\n")
    for name, wire, cc in ENVELOPE:
        sl = "envelope." + re.sub(r"[^a-z0-9]+", "_", wire)
        out.append(f"    val {name}: EnvelopeMember = EnvelopeMember(id = {kstr(name)}, wire = {kstr(wire)}, "
                   f"ccSection = {kstr(cc)}, labelKey = {kstr('ceg.' + sl + '.label')}, glossKey = {kstr('ceg.' + sl + '.gloss')})\n")
    out.append("\n    val all: List<EnvelopeMember> = listOf(" + ", ".join(n for n, _, _ in ENVELOPE) + ")\n")
    out.append("}\n")

    if missing_gloss:
        print(f"[note] {len(missing_gloss)} of {len(rows)} families have no gloss yet (they fall back to the "
              f"registry description); the UI touches none of them today.", file=sys.stderr)
    return "".join(out)


def _rel(p: pathlib.Path) -> str:
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p)


def check(registry: pathlib.Path, glosses: pathlib.Path, renderers: pathlib.Path, en: pathlib.Path,
          target: pathlib.Path) -> int:
    try:
        want = build(registry, glosses, renderers, en)
    except Refusal as e:
        print(f"[FAIL] {e}")
        return 1
    if not target.exists():
        print(f"[FAIL] {_rel(target)} is missing — run --write")
        return 1
    if target.read_text(encoding="utf-8") != want:
        print(f"[FAIL] {_rel(target)} is stale — run --write")
        return 1
    print(f"[OK] {_rel(target)} is current ({want.count('    val ') - 2} entries)")
    return 0


def self_test() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        t = pathlib.Path(tmp)
        reg, glo, ren, en, tgt = (t / "r.json", t / "g.json", t / "rn.json", t / "en.json", t / "D.kt")
        shutil.copy(REGISTRY, reg); shutil.copy(GLOSSES, glo); shutil.copy(RENDERERS, ren); shutil.copy(EN_JSON, en)
        tgt.write_text(build(reg, glo, ren, en), encoding="utf-8")
        if check(reg, glo, ren, en, tgt) != 0:
            print("[FAIL] self-test: a fresh build did not pass --check"); return 1
        # (a) a gloss for a family that does not exist
        g = json.loads(glo.read_text()); g["bogus:{x}"] = {"label": "x", "gloss": "y"}
        glo.write_text(json.dumps(g))
        if check(reg, glo, ren, en, tgt) == 0:
            print("[FAIL] self-test: an unregistered gloss key did not go red"); return 1
        shutil.copy(GLOSSES, glo)
        # (b) an override that contradicts polarity
        r = json.loads(ren.read_text()); r["prohibited:{category}"] = "SIGNED_SCORE"
        ren.write_text(json.dumps(r))
        if check(reg, glo, ren, en, tgt) == 0:
            print("[FAIL] self-test: a polarity-contradicting override did not go red"); return 1
        shutil.copy(RENDERERS, ren)
        # (c) a dropped registry row
        d = json.loads(reg.read_text()); d["families"] = d["families"][1:]
        reg.write_text(json.dumps(d))
        if check(reg, glo, ren, en, tgt) == 0:
            print("[FAIL] self-test: a changed registry did not go red"); return 1
        shutil.copy(REGISTRY, reg)
        # (d) an emitted key that no longer resolves
        e = json.loads(en.read_text()); del e["ceg"]["consent_kind"]["gloss"]
        en.write_text(json.dumps(e))
        if check(reg, glo, ren, en, tgt) == 0:
            print("[FAIL] self-test: an unresolvable localization key did not go red"); return 1
    print("[OK] self-test: the check goes red on four deliberate breaks")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return self_test()
    if args.write:
        try:
            text = build(REGISTRY, GLOSSES, RENDERERS, EN_JSON)
        except Refusal as e:
            print(f"[FAIL] {e}"); return 1
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(text, encoding="utf-8")
        print(f"[OK] wrote {_rel(TARGET)}")
        return 0
    return check(REGISTRY, GLOSSES, RENDERERS, EN_JSON, TARGET)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
