#!/usr/bin/env python3
"""The 71 glyphs, generated from the design's path data — never hand-drawn twice.

    python3 client/tools/gen_glyphs.py --write       # regenerate CirisGlyphs.kt
    python3 client/tools/gen_glyphs.py --check       # fail if the committed file is stale
    python3 client/tools/gen_glyphs.py --self-test   # prove --check goes red on a break

SOURCE: `client/design/icon-paths.json`, vendored from the Claude Design
project's Locked Spec (ICONS table): 22x22 viewBox, stroke 1.75, square caps,
miter joins. Four glyphs carry dashed segments (file-gone, share-out, pull-in,
blurred); ImageVector cannot dash, so the generated table keeps the dash
intervals and `ui/glyphs/Glyph.kt` draws them on a Canvas.

The generated file names NO colour: a glyph is path data, and `Glyph(tint=)`
paints it from a token. That is what keeps the colour-literal lint's exemption
list at exactly one file.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import shutil
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "design" / "icon-paths.json"
TARGET = (ROOT / "shared" / "src" / "commonMain" / "kotlin" / "ai" / "ciris" / "mobile"
          / "shared" / "ui" / "glyphs" / "CirisGlyphs.kt")

HEADER = """// GENERATED by client/tools/gen_glyphs.py from client/design/icon-paths.json — do not edit.
// Re-run `python3 client/tools/gen_glyphs.py --write` after changing the source.
package ai.ciris.mobile.shared.ui.glyphs

/** One path of a glyph: SVG path data plus how it is painted. No colour lives here. */
class GlyphSeg(
    val d: String,
    val fill: Boolean,
    val stroke: Boolean,
    /** Dash intervals in viewbox units, or null for a solid stroke. */
    val dash: FloatArray?,
)

const val GLYPH_VIEWBOX = 22f
const val GLYPH_STROKE = 1.75f

"""


def kotlin_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).upper()


def load(source: pathlib.Path) -> dict:
    data = json.loads(source.read_text(encoding="utf-8"))
    glyphs = data["glyphs"]
    if not glyphs:
        raise SystemExit(f"[FAIL] {source}: no glyphs — the source is empty or the shape changed")
    return glyphs


def render(glyphs: dict) -> str:
    out = [HEADER]
    out.append("enum class GlyphName(val id: String) {\n")
    names = sorted(glyphs)
    for i, name in enumerate(names):
        sep = "," if i < len(names) - 1 else ";"
        out.append(f'    {kotlin_name(name)}("{name}"){sep}\n')
    out.append("\n    companion object {\n")
    out.append("        fun byId(id: String): GlyphName? = entries.firstOrNull { it.id == id }\n")
    out.append("    }\n}\n\n")
    out.append("val GLYPH_SEGMENTS: Map<GlyphName, List<GlyphSeg>> = mapOf(\n")
    dropped = []
    for name in names:
        segs = []
        for seg in glyphs[name]:
            if not seg["fill"] and not seg["stroke"]:
                dropped.append(name)
                continue
            dash = seg["dash"]
            dash_kt = ("floatArrayOf(" + ", ".join(f"{float(x)}f" for x in dash) + ")") if dash else "null"
            d = seg["d"].replace("\\", "\\\\").replace('"', '\\"')
            segs.append(f'        GlyphSeg("{d}", fill = {"true" if seg["fill"] else "false"}, '
                        f'stroke = {"true" if seg["stroke"] else "false"}, dash = {dash_kt}),\n')
        out.append(f"    GlyphName.{kotlin_name(name)} to listOf(\n")
        out.extend(segs)
        out.append("    ),\n")
    out.append(")\n")
    if dropped:
        print(f"[note] dropped {len(dropped)} segment(s) that paint nothing (fill none, stroke none): "
              + ", ".join(sorted(set(dropped))), file=sys.stderr)
    return "".join(out)


def _rel(p: pathlib.Path) -> str:
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p)


def check(source: pathlib.Path, target: pathlib.Path) -> int:
    want = render(load(source))
    if not target.exists():
        print(f"[FAIL] {target} is missing — run --write")
        return 1
    have = target.read_text(encoding="utf-8")
    if have != want:
        print(f"[FAIL] {_rel(target)} is stale against {_rel(source)} — run --write")
        return 1
    n = want.count('    GlyphName.')
    print(f"[OK] {_rel(target)} is current ({n} glyphs)")
    return 0


def self_test() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        tmpd = pathlib.Path(tmp)
        src = tmpd / "icon-paths.json"
        tgt = tmpd / "CirisGlyphs.kt"
        shutil.copy(SOURCE, src)
        tgt.write_text(render(load(src)), encoding="utf-8")
        if check(src, tgt) != 0:
            print("[FAIL] self-test: a fresh render did not pass --check")
            return 1
        data = json.loads(src.read_text(encoding="utf-8"))
        first = sorted(data["glyphs"])[0]
        del data["glyphs"][first]
        src.write_text(json.dumps(data), encoding="utf-8")
        if check(src, tgt) == 0:
            print("[FAIL] self-test: dropping a glyph from the source did not go red")
            return 1
    print("[OK] self-test: the check goes red on a deliberate break")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return self_test()
    if args.write:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(render(load(SOURCE)), encoding="utf-8")
        print(f"[OK] wrote {TARGET.relative_to(ROOT)}")
        return 0
    return check(SOURCE, TARGET)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
