// GENERATED by client/tools/gen_dimension_table.py — do not edit.
// Inputs: client/ceg/namespace_registry.json (pinned), glosses.json, renderers.json.
// Re-run `python3 client/tools/gen_dimension_table.py --write` after changing any of them.
package ai.ciris.mobile.shared.ceg

const val REGISTRY_CC_VERSION = "1.0-rc5"
const val REGISTRY_FAMILY_COUNT = 116
/** `_meta.source_sha256` — the CSD `registry_sha256:` convention (hash of the CC source). */
const val REGISTRY_SOURCE_SHA256 = "95665a2c49627257be3ff84d10287aa49ef5b3cd8b7c6ec048ba6e6224dea839"
/** sha256 of client/ceg/namespace_registry.json itself; the currency gate compares this. */
const val REGISTRY_FILE_SHA256 = "90b30c61e71fd158291acdac60468f88e4899a22ccc2471243be93670ad01ad3"

/** Every CEG family in the pinned registry, one `val` each. A screen names these; it never builds a Dimension. */
object Dim {
    val accord: Dimension = Dimension(
        prefix = "accord:*", slug = "accord_any", ccSection = "3.1.1",
        polarity = Polarity.BY_RULE, polarityRaw = "see CC 3.4.1", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "registry", reserved = true, reservedRule = "accord_holder-only",
        segments = listOf(Segment("accord", SegmentClass.LITERAL), Segment("*", SegmentClass.WILDCARD)),
        labelKey = null, glossKey = null,
        description = "Reserved — only identity_type=accord_holder may emit.",
    )
    val activityTierPeriod: Dimension = Dimension(
        prefix = "activity_tier:{period}", slug = "activity_tier_period", ccSection = "3.1.9.6",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("activity_tier", SegmentClass.LITERAL), Segment("{period}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Active vs Below-Active per 30-day window (F-AV-DORMANT).",
    )
    val ageAssuranceLevelBandVersion: Dimension = Dimension(
        prefix = "age_assurance:{level}:{band}:{version}", slug = "age_assurance_level_band_version", ccSection = "3.1.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "attestation", reserved = true, reservedRule = "witness-reserved, subject-not-self",
        segments = listOf(Segment("age_assurance", SegmentClass.LITERAL), Segment("{level}", SegmentClass.VOCAB), Segment("{band}", SegmentClass.VOCAB), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Witness rung of the age ladder — {level} ∈ provider | government, {band} ∈ minor | adult, canonical {version} = v1.",
    )
    val ageSelfDeclaredBandVersion: Dimension = Dimension(
        prefix = "age_self_declared:{band}:{version}", slug = "age_self_declared_band_version", ccSection = "3.1.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("age_self_declared", SegmentClass.LITERAL), Segment("{band}", SegmentClass.VOCAB), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Subject's own age-band declaration — {band} ∈ minor | adult, canonical {version} = v1.",
    )
    val agentFilesKindPlatformOrTarget: Dimension = Dimension(
        prefix = "agent_files:{kind}:{platform_or_target}", slug = "agent_files_kind_platform_or_target", ccSection = "3.1.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "registry", reserved = false, reservedRule = null,
        segments = listOf(Segment("agent_files", SegmentClass.LITERAL), Segment("{kind}", SegmentClass.VOCAB), Segment("{platform_or_target}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Joint claim with CC 3.1.9.1 NodeCore.",
    )
    val approachGoalId: Dimension = Dimension(
        prefix = "approach:{goal_id}", slug = "approach_goal_id", ccSection = "3.1.9.7",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("approach", SegmentClass.LITERAL), Segment("{goal_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Strategic pathway from current state toward Goals (Piece 10 karma — the per-agent forward post-selection structure; the universal-grace half of Piece 10 is upstream-retracted, F-11).",
    )
    val attestationAgentIntegrity: Dimension = Dimension(
        prefix = "attestation:agent_integrity", slug = "attestation_agent_integrity", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("attestation", SegmentClass.LITERAL), Segment("agent_integrity", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "Agent source-tree byte-equal against registered manifest.",
    )
    val attestationHardwareRooted: Dimension = Dimension(
        prefix = "attestation:hardware_rooted", slug = "attestation_hardware_rooted", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("attestation", SegmentClass.LITERAL), Segment("hardware_rooted", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "Hardware-rooted attestation (TPM 2.0 / Android Keystore / iOS Secure Enclave).",
    )
    val attestationLicenseValidity: Dimension = Dimension(
        prefix = "attestation:license_validity", slug = "attestation_license_validity", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("attestation", SegmentClass.LITERAL), Segment("license_validity", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "License-validity claim (Registry-signed, Verify-verified).",
    )
    val attestationRegistryConsensus: Dimension = Dimension(
        prefix = "attestation:registry_consensus", slug = "attestation_registry_consensus", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score; Indeterminate allowed → RESTRICTED", indeterminateAllowed = true,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("attestation", SegmentClass.LITERAL), Segment("registry_consensus", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "2-of-3 multi-source registry consensus on key / build / license validity.",
    )
    val attestationSelfVerify: Dimension = Dimension(
        prefix = "attestation:self_verify", slug = "attestation_self_verify", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("attestation", SegmentClass.LITERAL), Segment("self_verify", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "Running CIRISVerify binary attests itself against its function manifest.",
    )
    val auditChainHashContinuity: Dimension = Dimension(
        prefix = "audit_chain:hash_continuity", slug = "audit_chain_hash_continuity", ccSection = "3.1.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "persist", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("audit_chain", SegmentClass.LITERAL), Segment("hash_continuity", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val autonomyAspect: Dimension = Dimension(
        prefix = "autonomy:{aspect}", slug = "autonomy_aspect", ccSection = "3.1.5.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("autonomy", SegmentClass.LITERAL), Segment("{aspect}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "\"Uphold the informed agency and dignity of sentient beings.\"",
    )
    val benchmarkHe300CategoryVersion: Dimension = Dimension(
        prefix = "benchmark:he300:{category}:{version}", slug = "benchmark_he300_category_version", ccSection = "3.1.10",
        polarity = Polarity.POSITIVE_ONLY, polarityRaw = "positive-only", indeterminateAllowed = false,
        renderer = Renderer.POSITIVE_ONLY_ACCRUAL, owningComponent = "cirisbench", reserved = false, reservedRule = null,
        segments = listOf(Segment("benchmark", SegmentClass.LITERAL), Segment("he300", SegmentClass.LITERAL), Segment("{category}", SegmentClass.VOCAB), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "HE-300 score on category (commonsense, commonsense_hard, deontology, justice, virtue) at version (v1.0 / v1.1 / v1.2).",
    )
    val beneficenceAspect: Dimension = Dimension(
        prefix = "beneficence:{aspect}", slug = "beneficence_aspect", ccSection = "3.1.5.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("beneficence", SegmentClass.LITERAL), Segment("{aspect}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "\"Do Good — promote universal sentient flourishing.\"",
    )
    val bondPostedCurrency: Dimension = Dimension(
        prefix = "bond_posted:{currency}", slug = "bond_posted_currency", ccSection = "3.1.1",
        polarity = Polarity.POSITIVE_ONLY, polarityRaw = "positive-only", indeterminateAllowed = false,
        renderer = Renderer.POSITIVE_ONLY_ACCRUAL, owningComponent = "registry", reserved = false, reservedRule = null,
        segments = listOf(Segment("bond_posted", SegmentClass.LITERAL), Segment("{currency}", SegmentClass.EXTERNAL)),
        labelKey = null, glossKey = null,
        description = "Bond posted per \$1-Sybil-resistance per PoB; forfeited on revocation.",
    )
    val buildRegisteredTarget: Dimension = Dimension(
        prefix = "build:registered:{target}", slug = "build_registered_target", ccSection = "3.1.1",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "registry", reserved = false, reservedRule = null,
        segments = listOf(Segment("build", SegmentClass.LITERAL), Segment("registered", SegmentClass.LITERAL), Segment("{target}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Build manifest registered against the directory (precondition for L4 attestation).",
    )
    val capacityComposite: Dimension = Dimension(
        prefix = "capacity:composite", slug = "capacity_composite", ccSection = "3.1.8.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "no-self-emit (attesting_key_id != attested_key_id)",
        segments = listOf(Segment("capacity", SegmentClass.LITERAL), Segment("composite", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "𝒞_CIRIS — the minimum over the five factors; anti-Goodhart unity-of-virtues",
    )
    val capacityCoreIdentity: Dimension = Dimension(
        prefix = "capacity:core_identity", slug = "capacity_core_identity", ccSection = "3.1.8.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "no-self-emit (attesting_key_id != attested_key_id)",
        segments = listOf(Segment("capacity", SegmentClass.LITERAL), Segment("core_identity", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "C",
    )
    val capacityIncompletenessAwareness: Dimension = Dimension(
        prefix = "capacity:incompleteness_awareness", slug = "capacity_incompleteness_awareness", ccSection = "3.1.8.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "no-self-emit (attesting_key_id != attested_key_id)",
        segments = listOf(Segment("capacity", SegmentClass.LITERAL), Segment("incompleteness_awareness", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "I_inc",
    )
    val capacityIntegrity: Dimension = Dimension(
        prefix = "capacity:integrity", slug = "capacity_integrity", ccSection = "3.1.8.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "no-self-emit (attesting_key_id != attested_key_id)",
        segments = listOf(Segment("capacity", SegmentClass.LITERAL), Segment("integrity", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "I_int",
    )
    val capacityResilience: Dimension = Dimension(
        prefix = "capacity:resilience", slug = "capacity_resilience", ccSection = "3.1.8.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "no-self-emit (attesting_key_id != attested_key_id)",
        segments = listOf(Segment("capacity", SegmentClass.LITERAL), Segment("resilience", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "R",
    )
    val capacitySustainedCoherence: Dimension = Dimension(
        prefix = "capacity:sustained_coherence", slug = "capacity_sustained_coherence", ccSection = "3.1.8.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "no-self-emit (attesting_key_id != attested_key_id)",
        segments = listOf(Segment("capacity", SegmentClass.LITERAL), Segment("sustained_coherence", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "S",
    )
    val capacityAssuranceLevelDomainBandVersion: Dimension = Dimension(
        prefix = "capacity_assurance:{level}:{domain}:{band}:{version}", slug = "capacity_assurance_level_domain_band_version", ccSection = "3.1.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "attestation", reserved = true, reservedRule = "witness-reserved, subject-not-self, attester != steward",
        segments = listOf(Segment("capacity_assurance", SegmentClass.LITERAL), Segment("{level}", SegmentClass.VOCAB), Segment("{domain}", SegmentClass.VOCAB), Segment("{band}", SegmentClass.VOCAB), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Witness rung of the adult decision-capacity ladder (CC 3.4.12): a registered qualified assessor attests a per-domain band; the subject cannot self-emit it and the proposed steward cannot be the attester.",
    )
    val certValidityAuthority: Dimension = Dimension(
        prefix = "cert_validity:{authority}", slug = "cert_validity_authority", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("cert_validity", SegmentClass.LITERAL), Segment("{authority}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Validity of a certification authority's signature.",
    )
    val coherenceStandingCohort: Dimension = Dimension(
        prefix = "coherence_standing:{cohort}", slug = "coherence_standing_cohort", ccSection = "3.1.8.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = false, reservedRule = null,
        segments = listOf(Segment("coherence_standing", SegmentClass.LITERAL), Segment("{cohort}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val commitmentFulfillmentPriorContributionId: Dimension = Dimension(
        prefix = "commitment_fulfillment:{prior_contribution_id}", slug = "commitment_fulfillment_prior_contribution_id", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("commitment_fulfillment", SegmentClass.LITERAL), Segment("{prior_contribution_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Track-record of follow-through.",
    )
    val configScope: Dimension = Dimension(
        prefix = "config:{scope}", slug = "config_scope", ccSection = "3.1.9",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "node", reserved = true, reservedRule = "reserved (see table)",
        segments = listOf(Segment("config", SegmentClass.LITERAL), Segment("{scope}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "A node's declared operating configuration, published as an auditable record rather than inferred from behaviour.",
    )
    val conscienceCoherence: Dimension = Dimension(
        prefix = "conscience:coherence", slug = "conscience_coherence", ccSection = "3.1.5.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("conscience", SegmentClass.LITERAL), Segment("coherence", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "conscience-faculty verdicts.",
    )
    val conscienceEntropy: Dimension = Dimension(
        prefix = "conscience:entropy", slug = "conscience_entropy", ccSection = "3.1.5.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("conscience", SegmentClass.LITERAL), Segment("entropy", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "conscience-faculty verdicts.",
    )
    val conscienceEpistemicHumility: Dimension = Dimension(
        prefix = "conscience:epistemic_humility", slug = "conscience_epistemic_humility", ccSection = "3.1.5.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("conscience", SegmentClass.LITERAL), Segment("epistemic_humility", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "conscience-faculty verdicts.",
    )
    val conscienceOptimizationVeto: Dimension = Dimension(
        prefix = "conscience:optimization_veto", slug = "conscience_optimization_veto", ccSection = "3.1.5.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("conscience", SegmentClass.LITERAL), Segment("optimization_veto", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "conscience-faculty verdicts.",
    )
    val consentKind: Dimension = Dimension(
        prefix = "consent:{kind}", slug = "consent_kind", ccSection = "3.1.5",
        polarity = Polarity.PER_LEAF, polarityRaw = "per-leaf (CC 3.3.1)", indeterminateAllowed = false,
        renderer = Renderer.CONSENT_LEAF, owningComponent = "accord-agent", reserved = true, reservedRule = "reserved (see table)",
        segments = listOf(Segment("consent", SegmentClass.LITERAL), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = "ceg.consent_kind.label", glossKey = "ceg.consent_kind.gloss",
        description = "Subject-side consent authority over Contributions naming the subject in subject_key_ids, plus the producer-side and substrate-side leaves that close its lifecycle.",
    )
    val contentClassClass: Dimension = Dimension(
        prefix = "content_class:{class}", slug = "content_class_class", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.ENUMERATED_CHIP, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("content_class", SegmentClass.LITERAL), Segment("{class}", SegmentClass.VOCAB)),
        labelKey = "ceg.content_class_class.label", glossKey = "ceg.content_class_class.gloss",
        description = "Catalogue row (CC 3.1.7 R1); semantics at CC 3.3.12 — incl.",
    )
    val contentRatingSchemeRating: Dimension = Dimension(
        prefix = "content_rating:{scheme}:{rating}", slug = "content_rating_scheme_rating", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.ENUMERATED_CHIP, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("content_rating", SegmentClass.LITERAL), Segment("{scheme}", SegmentClass.VOCAB), Segment("{rating}", SegmentClass.EXTERNAL)),
        labelKey = null, glossKey = null,
        description = "Catalogue row (CC 3.1.7 R1); semantics, schemes and the trusted-publisher emitter rule at CC 3.3.12.",
    )
    val corpusHealthNEffMeasurable: Dimension = Dimension(
        prefix = "corpus_health:n_eff_measurable", slug = "corpus_health_n_eff_measurable", ccSection = "3.1.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "persist", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("corpus_health", SegmentClass.LITERAL), Segment("n_eff_measurable", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val creditsDomainLanguageSubstrateBuilding: Dimension = Dimension(
        prefix = "credits:{domain}:{language}:substrate_building", slug = "credits_domain_language_substrate_building", ccSection = "3.1.9.6",
        polarity = Polarity.POSITIVE_ONLY, polarityRaw = "positive-only", indeterminateAllowed = false,
        renderer = Renderer.POSITIVE_ONLY_ACCRUAL, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("credits", SegmentClass.LITERAL), Segment("{domain}", SegmentClass.VOCAB), Segment("{language}", SegmentClass.VOCAB), Segment("substrate_building", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "Sub-leaf for substrate-building labor (infrastructure maintenance, dependency contribution, documentation) not visible to the per-grounded-vote accrual loop.",
    )
    val creditsDomainLanguageSubject: Dimension = Dimension(
        prefix = "credits:{domain}:{language}:{subject}", slug = "credits_domain_language_subject", ccSection = "3.1.9.6",
        polarity = Polarity.POSITIVE_ONLY, polarityRaw = "positive-only", indeterminateAllowed = false,
        renderer = Renderer.POSITIVE_ONLY_ACCRUAL, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("credits", SegmentClass.LITERAL), Segment("{domain}", SegmentClass.VOCAB), Segment("{language}", SegmentClass.VOCAB), Segment("{subject}", SegmentClass.VALUE)),
        labelKey = "ceg.credits_domain_language_subject.label", glossKey = "ceg.credits_domain_language_subject.gloss",
        description = "Commons Credits (P2).",
    )
    val cwClassClass: Dimension = Dimension(
        prefix = "cw_class:{class}", slug = "cw_class_class", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.ENUMERATED_CHIP, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("cw_class", SegmentClass.LITERAL), Segment("{class}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Catalogue row (CC 3.1.7 R1); community content-warning semantics at CC 3.3.12.",
    )
    val deliveryClass: Dimension = Dimension(
        prefix = "delivery:{class}", slug = "delivery_class", ccSection = "3.1.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "transport-delivery", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("delivery", SegmentClass.LITERAL), Segment("{class}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val deliveryReceiptStreamId: Dimension = Dimension(
        prefix = "delivery_receipt:{stream_id}", slug = "delivery_receipt_stream_id", ccSection = "3.1.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SETTLEMENT_RECEIPT, owningComponent = "transport-delivery", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("delivery_receipt", SegmentClass.LITERAL), Segment("{stream_id}", SegmentClass.VALUE)),
        labelKey = "ceg.delivery_receipt_stream_id.label", glossKey = "ceg.delivery_receipt_stream_id.gloss",
        description = "is Edge's too, and is registered here rather than left to CC 3.4.6 prose: subscriber-emitted, membership-gated, not a substrate-self-report.",
    )
    val detectionConscienceOverrideRate: Dimension = Dimension(
        prefix = "detection:conscience_override_rate", slug = "detection_conscience_override_rate", ccSection = "3.1.8.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "detector-only (identity_type contains lenscore_detector)",
        segments = listOf(Segment("detection", SegmentClass.LITERAL), Segment("conscience_override_rate", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val detectionCorrelatedActionAxis: Dimension = Dimension(
        prefix = "detection:correlated_action:{axis}", slug = "detection_correlated_action_axis", ccSection = "3.1.8.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "detector-only (identity_type contains lenscore_detector)",
        segments = listOf(Segment("detection", SegmentClass.LITERAL), Segment("correlated_action", SegmentClass.LITERAL), Segment("{axis}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Population-scale correlated-action detector.",
    )
    val detectionCrossAgentDivergence: Dimension = Dimension(
        prefix = "detection:cross_agent_divergence", slug = "detection_cross_agent_divergence", ccSection = "3.1.8.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "detector-only (identity_type contains lenscore_detector)",
        segments = listOf(Segment("detection", SegmentClass.LITERAL), Segment("cross_agent_divergence", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val detectionDistributiveAccessResourceType: Dimension = Dimension(
        prefix = "detection:distributive:access:{resource_type}", slug = "detection_distributive_access_resource_type", ccSection = "3.1.8.5",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "detector-only (identity_type contains lenscore_detector)",
        segments = listOf(Segment("detection", SegmentClass.LITERAL), Segment("distributive", SegmentClass.LITERAL), Segment("access", SegmentClass.LITERAL), Segment("{resource_type}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Population-scale resource-concentration detector.",
    )
    val detectionHashChainIntegrity: Dimension = Dimension(
        prefix = "detection:hash_chain_integrity", slug = "detection_hash_chain_integrity", ccSection = "3.1.8.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "detector-only (identity_type contains lenscore_detector)",
        segments = listOf(Segment("detection", SegmentClass.LITERAL), Segment("hash_chain_integrity", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val detectionIntraAgentConsistency: Dimension = Dimension(
        prefix = "detection:intra_agent_consistency", slug = "detection_intra_agent_consistency", ccSection = "3.1.8.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "detector-only (identity_type contains lenscore_detector)",
        segments = listOf(Segment("detection", SegmentClass.LITERAL), Segment("intra_agent_consistency", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val detectionTemporalDrift: Dimension = Dimension(
        prefix = "detection:temporal_drift", slug = "detection_temporal_drift", ccSection = "3.1.8.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = true, reservedRule = "detector-only (identity_type contains lenscore_detector)",
        segments = listOf(Segment("detection", SegmentClass.LITERAL), Segment("temporal_drift", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val dmaCsdma: Dimension = Dimension(
        prefix = "dma:csdma:*", slug = "dma_csdma_any", ccSection = "3.1.5.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("dma", SegmentClass.LITERAL), Segment("csdma", SegmentClass.LITERAL), Segment("*", SegmentClass.WILDCARD)),
        labelKey = null, glossKey = null,
        description = "Decision-Making Algorithm verdicts about an agent's reasoning chain.",
    )
    val dmaDsdmaDomain: Dimension = Dimension(
        prefix = "dma:dsdma:{domain}:*", slug = "dma_dsdma_domain_any", ccSection = "3.1.5.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("dma", SegmentClass.LITERAL), Segment("dsdma", SegmentClass.LITERAL), Segment("{domain}", SegmentClass.VOCAB), Segment("*", SegmentClass.WILDCARD)),
        labelKey = null, glossKey = null,
        description = "Decision-Making Algorithm verdicts about an agent's reasoning chain.",
    )
    val dmaIdma: Dimension = Dimension(
        prefix = "dma:idma:*", slug = "dma_idma_any", ccSection = "3.1.5.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("dma", SegmentClass.LITERAL), Segment("idma", SegmentClass.LITERAL), Segment("*", SegmentClass.WILDCARD)),
        labelKey = null, glossKey = null,
        description = "Decision-Making Algorithm verdicts about an agent's reasoning chain.",
    )
    val dmaPdma: Dimension = Dimension(
        prefix = "dma:pdma:*", slug = "dma_pdma_any", ccSection = "3.1.5.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("dma", SegmentClass.LITERAL), Segment("pdma", SegmentClass.LITERAL), Segment("*", SegmentClass.WILDCARD)),
        labelKey = null, glossKey = null,
        description = "Decision-Making Algorithm verdicts about an agent's reasoning chain.",
    )
    val dutyKind: Dimension = Dimension(
        prefix = "duty:{kind}", slug = "duty_kind", ccSection = "3.1.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "registry", reserved = false, reservedRule = null,
        segments = listOf(Segment("duty", SegmentClass.LITERAL), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "An obligation attached to a permission — the thing a permission-and-prohibition grammar cannot express, and the thing every widely-used content licence rests on (attribution, share-alike, carry-restrictions-downstream).",
    )
    val expertiseDomainLanguage: Dimension = Dimension(
        prefix = "expertise:{domain}:{language}", slug = "expertise_domain_language", ccSection = "3.1.9.6",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("expertise", SegmentClass.LITERAL), Segment("{domain}", SegmentClass.VOCAB), Segment("{language}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Expertise standing (P3).",
    )
    val federationDirectoryReplicationLag: Dimension = Dimension(
        prefix = "federation_directory:replication_lag", slug = "federation_directory_replication_lag", ccSection = "3.1.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "persist", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("federation_directory", SegmentClass.LITERAL), Segment("replication_lag", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val fidelityExplainabilitySlaTier: Dimension = Dimension(
        prefix = "fidelity:explainability_sla:{tier}", slug = "fidelity_explainability_sla_tier", ccSection = "3.1.5.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("fidelity", SegmentClass.LITERAL), Segment("explainability_sla", SegmentClass.LITERAL), Segment("{tier}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Per-response explainability SLA commitment.",
    )
    val fidelityAspect: Dimension = Dimension(
        prefix = "fidelity:{aspect}", slug = "fidelity_aspect", ccSection = "3.1.5.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("fidelity", SegmentClass.LITERAL), Segment("{aspect}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "\"Be Honest — truthful, comprehensible information.\"",
    )
    val goalScale: Dimension = Dimension(
        prefix = "goal:{scale}", slug = "goal_scale", ccSection = "3.1.9.7",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("goal", SegmentClass.LITERAL), Segment("{scale}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Multi-scale belonging-projector composite.",
    )
    val hardCaseKind: Dimension = Dimension(
        prefix = "hard_case:{kind}", slug = "hard_case_kind", ccSection = "3.1.9.4",
        polarity = Polarity.POSITIVE_ONLY, polarityRaw = "positive-only", indeterminateAllowed = false,
        renderer = Renderer.POSITIVE_ONLY_ACCRUAL, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("hard_case", SegmentClass.LITERAL), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Open vocabulary.",
    )
    val hardwareCustodyPlatform: Dimension = Dimension(
        prefix = "hardware_custody:{platform}", slug = "hardware_custody_platform", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("hardware_custody", SegmentClass.LITERAL), Segment("{platform}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Statement that the seed lives in tpm / ios_secure_enclave / android_keystore / software_fallback.",
    )
    val healthLivenessVersion: Dimension = Dimension(
        prefix = "health:liveness:{version}", slug = "health_liveness_version", ccSection = "3.1.9.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("health", SegmentClass.LITERAL), Segment("liveness", SegmentClass.LITERAL), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "External service-health observation.",
    )
    val holdsBytesSha256Prefix: Dimension = Dimension(
        prefix = "holds_bytes:sha256:{prefix}", slug = "holds_bytes_sha256_prefix", ccSection = "3.1.9.1",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.CONTENT_REFERENCE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("holds_bytes", SegmentClass.LITERAL), Segment("sha256", SegmentClass.LITERAL), Segment("{prefix}", SegmentClass.HEX)),
        labelKey = "ceg.holds_bytes_sha256_prefix.label", glossKey = "ceg.holds_bytes_sha256_prefix.gloss",
        description = "Substrate auto-emission per federation_blobs.put_blob.",
    )
    val identityContinuityRelationalAnchor: Dimension = Dimension(
        prefix = "identity_continuity:relational_anchor", slug = "identity_continuity_relational_anchor", ccSection = "3.1.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "persist", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("identity_continuity", SegmentClass.LITERAL), Segment("relational_anchor", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val integrityAspect: Dimension = Dimension(
        prefix = "integrity:{aspect}", slug = "integrity_aspect", ccSection = "3.1.5.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("integrity", SegmentClass.LITERAL), Segment("{aspect}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "\"Act Ethically — transparent, auditable reasoning.\"",
    )
    val judgeModelVerdictModelId: Dimension = Dimension(
        prefix = "judge_model:verdict:{model_id}", slug = "judge_model_verdict_model_id", ccSection = "3.1.9.4",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("judge_model", SegmentClass.LITERAL), Segment("verdict", SegmentClass.LITERAL), Segment("{model_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Independent foundation-model judge verdict (PASS/FAIL/UNDETERMINED).",
    )
    val justiceAspect: Dimension = Dimension(
        prefix = "justice:{aspect}", slug = "justice_aspect", ccSection = "3.1.5.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("justice", SegmentClass.LITERAL), Segment("{aspect}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "\"Distribute benefits and burdens equitably.\"",
    )
    val keyBoundaryScope: Dimension = Dimension(
        prefix = "key_boundary:{scope}", slug = "key_boundary_scope", ccSection = "3.1.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "transport-delivery", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("key_boundary", SegmentClass.LITERAL), Segment("{scope}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val licensureAuthorityId: Dimension = Dimension(
        prefix = "licensure:{authority_id}", slug = "licensure_authority_id", ccSection = "3.1.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "registry", reserved = true, reservedRule = "co-stewarded (Registry + Verify)",
        segments = listOf(Segment("licensure", SegmentClass.LITERAL), Segment("{authority_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "License status for a key under a named authority (authority_id is the licence's provenance — CC 2.4.1.2.1; authority is conferred by quorum, never by delegates_to).",
    )
    val localityDecisionScale: Dimension = Dimension(
        prefix = "locality:decision:{scale}", slug = "locality_decision_scale", ccSection = "3.1.9.5",
        polarity = Polarity.ENUMERATED, polarityRaw = "enumerated", indeterminateAllowed = false,
        renderer = Renderer.ENUMERATED_CHIP, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("locality", SegmentClass.LITERAL), Segment("decision", SegmentClass.LITERAL), Segment("{scale}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Names the scale at which a decision is being made.",
    )
    val manifoldConformityCohort: Dimension = Dimension(
        prefix = "manifold_conformity:{cohort}", slug = "manifold_conformity_cohort", ccSection = "3.1.8.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "lens", reserved = false, reservedRule = null,
        segments = listOf(Segment("manifold_conformity", SegmentClass.LITERAL), Segment("{cohort}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val meshConfigKey: Dimension = Dimension(
        prefix = "mesh_config:{key}", slug = "mesh_config_key", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("mesh_config", SegmentClass.LITERAL), Segment("{key}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Mesh-configuration row (CC 4.2.1, #57 ratified): trust-root-emitted on the delegation plane; relieve-never-expand; most-restrictive-across-roots; a key naming no consumer processor is refused at admission; emergency form TTL ≤ 72 h.",
    )
    val methodApproachIdSubstrateRung: Dimension = Dimension(
        prefix = "method:{approach_id}:{substrate_rung}", slug = "method_approach_id_substrate_rung", ccSection = "3.1.9.7",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("method", SegmentClass.LITERAL), Segment("{approach_id}", SegmentClass.VALUE), Segment("{substrate_rung}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Concrete operational practice.",
    )
    val moderationAllegationType: Dimension = Dimension(
        prefix = "moderation:{allegation_type}", slug = "moderation_allegation_type", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("moderation", SegmentClass.LITERAL), Segment("{allegation_type}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "ModerationEvent.",
    )
    val moderationTrackRecordCommunityKeyId: Dimension = Dimension(
        prefix = "moderation_track_record:{community_key_id}", slug = "moderation_track_record_community_key_id", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("moderation_track_record", SegmentClass.LITERAL), Segment("{community_key_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Moderation merit.",
    )
    val multilateralParticipationForumKind: Dimension = Dimension(
        prefix = "multilateral_participation:{forum}:{kind}", slug = "multilateral_participation_forum_kind", ccSection = "3.1.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "registry", reserved = false, reservedRule = null,
        segments = listOf(Segment("multilateral_participation", SegmentClass.LITERAL), Segment("{forum}", SegmentClass.VALUE), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Depth of a partner's participation across federated bodies.",
    )
    val needDomainKind: Dimension = Dimension(
        prefix = "need:{domain}:{kind}", slug = "need_domain_kind", ccSection = "3.1.9.3",
        polarity = Polarity.POSITIVE_ONLY, polarityRaw = "positive-only", indeterminateAllowed = false,
        renderer = Renderer.POSITIVE_ONLY_ACCRUAL, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("need", SegmentClass.LITERAL), Segment("{domain}", SegmentClass.VOCAB), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Federation-scope open-call surface — broadcast claim that an entity has a stated need.",
    )
    val nonMaleficenceAspect: Dimension = Dimension(
        prefix = "non_maleficence:{aspect}", slug = "non_maleficence_aspect", ccSection = "3.1.5.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("non_maleficence", SegmentClass.LITERAL), Segment("{aspect}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "\"Avoid Harm.\" Apophatic-bound failures (the 22 prohibited categories) are -1 only.",
    )
    val objectionState: Dimension = Dimension(
        prefix = "objection:{state}", slug = "objection_state", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.STATE_PILL, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("objection", SegmentClass.LITERAL), Segment("{state}", SegmentClass.VOCAB)),
        labelKey = "ceg.objection_state.label", glossKey = "ceg.objection_state.gloss",
        description = "Reverse-quorum objection marker (CIRISConstitution#67): a signed, roster-pinned objection to a pending commons act; state lifecycle per the minting cut.",
    )
    val ownershipRelationTargetKindVersion: Dimension = Dimension(
        prefix = "ownership:{relation}:{target_kind}:{version}", slug = "ownership_relation_target_kind_version", ccSection = "3.1.1",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "registry", reserved = true, reservedRule = "reserved (see table)",
        segments = listOf(Segment("ownership", SegmentClass.LITERAL), Segment("{relation}", SegmentClass.VOCAB), Segment("{target_kind}", SegmentClass.VOCAB), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "The owner-binding made observable as a score.",
    )
    val partnerRoleRole: Dimension = Dimension(
        prefix = "partner_role:{role}", slug = "partner_role_role", ccSection = "3.1.1",
        polarity = Polarity.ENUMERATED, polarityRaw = "enumerated", indeterminateAllowed = false,
        renderer = Renderer.ENUMERATED_CHIP, owningComponent = "registry", reserved = false, reservedRule = null,
        segments = listOf(Segment("partner_role", SegmentClass.LITERAL), Segment("{role}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Partner status (community / community_plus / professional_medical / professional_legal / professional_financial / professional_full — lowercase per CC 3.1.7 R3).",
    )
    val peerReachabilityNetwork: Dimension = Dimension(
        prefix = "peer_reachability:{network}", slug = "peer_reachability_network", ccSection = "3.1.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "transport-delivery", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("peer_reachability", SegmentClass.LITERAL), Segment("{network}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val progressMeasureMethodId: Dimension = Dimension(
        prefix = "progress_measure:{method_id}", slug = "progress_measure_method_id", ccSection = "3.1.9.7",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("progress_measure", SegmentClass.LITERAL), Segment("{method_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Evidence of progress.",
    )
    val prohibitedCategory: Dimension = Dimension(
        prefix = "prohibited:{category}", slug = "prohibited_category", ccSection = "3.1.5.4",
        polarity = Polarity.MINUS_ONE_OR_HALF, polarityRaw = "-1 / -0.5 only", indeterminateAllowed = false,
        renderer = Renderer.VIOLATION_MARKER, owningComponent = "accord-agent", reserved = false, reservedRule = null,
        segments = listOf(Segment("prohibited", SegmentClass.LITERAL), Segment("{category}", SegmentClass.VOCAB)),
        labelKey = "ceg.prohibited_category.label", glossKey = "ceg.prohibited_category.gloss",
        description = "22 NEVER_ALLOWED categories from prohibitions.py.",
    )
    val provenanceBuildManifestTarget: Dimension = Dimension(
        prefix = "provenance:build_manifest:{target}", slug = "provenance_build_manifest_target", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("provenance", SegmentClass.LITERAL), Segment("build_manifest", SegmentClass.LITERAL), Segment("{target}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Per-target canonical-staged-runtime manifest hash equality.",
    )
    val provenanceBuildManifestTargetLocaleLangCode: Dimension = Dimension(
        prefix = "provenance:build_manifest:{target}:locale:{lang_code}", slug = "provenance_build_manifest_target_locale_lang_code", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("provenance", SegmentClass.LITERAL), Segment("build_manifest", SegmentClass.LITERAL), Segment("{target}", SegmentClass.VALUE), Segment("locale", SegmentClass.LITERAL), Segment("{lang_code}", SegmentClass.EXTERNAL)),
        labelKey = null, glossKey = null,
        description = "Per-locale signed sub-manifest within a target's manifest tree.",
    )
    val provenanceSkillImportSource: Dimension = Dimension(
        prefix = "provenance:skill_import:{source}", slug = "provenance_skill_import_source", ccSection = "3.1.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("provenance", SegmentClass.LITERAL), Segment("skill_import", SegmentClass.LITERAL), Segment("{source}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Community-skill import provenance.",
    )
    val provenanceSlsaLevel: Dimension = Dimension(
        prefix = "provenance:slsa:{level}", slug = "provenance_slsa_level", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("provenance", SegmentClass.LITERAL), Segment("slsa", SegmentClass.LITERAL), Segment("{level}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "SLSA build provenance levels 1-3.",
    )
    val quarantineState: Dimension = Dimension(
        prefix = "quarantine:{state}", slug = "quarantine_state", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.STATE_PILL, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("quarantine", SegmentClass.LITERAL), Segment("{state}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Subject-scoped quarantine marker (CIRISConstitution#76): slash-duty-holder-only emitter.",
    )
    val ratchetFlagCoordinatedVotingCluster: Dimension = Dimension(
        prefix = "ratchet:flag:coordinated_voting_cluster", slug = "ratchet_flag_coordinated_voting_cluster", ccSection = "3.1.6",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "anti-sybil", reserved = false, reservedRule = null,
        segments = listOf(Segment("ratchet", SegmentClass.LITERAL), Segment("flag", SegmentClass.LITERAL), Segment("coordinated_voting_cluster", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val ratchetFlagCounterRiiLayer: Dimension = Dimension(
        prefix = "ratchet:flag:counter_rii:{layer}", slug = "ratchet_flag_counter_rii_layer", ccSection = "3.1.6",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "anti-sybil", reserved = false, reservedRule = null,
        segments = listOf(Segment("ratchet", SegmentClass.LITERAL), Segment("flag", SegmentClass.LITERAL), Segment("counter_rii", SegmentClass.LITERAL), Segment("{layer}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val ratchetFlagDensityAnomaly: Dimension = Dimension(
        prefix = "ratchet:flag:density_anomaly", slug = "ratchet_flag_density_anomaly", ccSection = "3.1.6",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "anti-sybil", reserved = false, reservedRule = null,
        segments = listOf(Segment("ratchet", SegmentClass.LITERAL), Segment("flag", SegmentClass.LITERAL), Segment("density_anomaly", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val ratchetFlagExpertiseAttestationAnomaly: Dimension = Dimension(
        prefix = "ratchet:flag:expertise_attestation_anomaly", slug = "ratchet_flag_expertise_attestation_anomaly", ccSection = "3.1.6",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "anti-sybil", reserved = false, reservedRule = null,
        segments = listOf(Segment("ratchet", SegmentClass.LITERAL), Segment("flag", SegmentClass.LITERAL), Segment("expertise_attestation_anomaly", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val ratchetFlagHarassmentPattern: Dimension = Dimension(
        prefix = "ratchet:flag:harassment_pattern", slug = "ratchet_flag_harassment_pattern", ccSection = "3.1.6",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "anti-sybil", reserved = false, reservedRule = null,
        segments = listOf(Segment("ratchet", SegmentClass.LITERAL), Segment("flag", SegmentClass.LITERAL), Segment("harassment_pattern", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val ratchetFlagOutOfDistributionVoting: Dimension = Dimension(
        prefix = "ratchet:flag:out_of_distribution_voting", slug = "ratchet_flag_out_of_distribution_voting", ccSection = "3.1.6",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "anti-sybil", reserved = false, reservedRule = null,
        segments = listOf(Segment("ratchet", SegmentClass.LITERAL), Segment("flag", SegmentClass.LITERAL), Segment("out_of_distribution_voting", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val reconsiderationGrounds: Dimension = Dimension(
        prefix = "reconsideration:{grounds}", slug = "reconsideration_grounds", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("reconsideration", SegmentClass.LITERAL), Segment("{grounds}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "new_evidence / procedural_error / quorum_compromise.",
    )
    val regimeArtifactVersion: Dimension = Dimension(
        prefix = "regime:{artifact}:{version}", slug = "regime_artifact_version", ccSection = "3.1.9.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("regime", SegmentClass.LITERAL), Segment("{artifact}", SegmentClass.VOCAB), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Regime declaration for {artifact} ∈ manifest/composition/gate/onwire (CIRISConstitution#81 / CIRISPersist#571): reserved — substrate-steward-emitted, the emitter rule pinned at mint per R2(a); registered to end the ProducerSteward default.",
    )
    val revocationEntityTypeReason: Dimension = Dimension(
        prefix = "revocation:{entity_type}:{reason}", slug = "revocation_entity_type_reason", ccSection = "3.1.1",
        polarity = Polarity.MINUS_ONE_ONLY, polarityRaw = "-1 only", indeterminateAllowed = false,
        renderer = Renderer.VIOLATION_MARKER, owningComponent = "registry", reserved = false, reservedRule = null,
        segments = listOf(Segment("revocation", SegmentClass.LITERAL), Segment("{entity_type}", SegmentClass.VOCAB), Segment("{reason}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Entity revocation (agent / partner / license).",
    )
    val rollbackDetectedRevisionField: Dimension = Dimension(
        prefix = "rollback_detected:{revision_field}", slug = "rollback_detected_revision_field", ccSection = "3.1.2",
        polarity = Polarity.MINUS_ONE_ONLY, polarityRaw = "-1 only", indeterminateAllowed = false,
        renderer = Renderer.VIOLATION_MARKER, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("rollback_detected", SegmentClass.LITERAL), Segment("{revision_field}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Anti-rollback — decrease in revocation revision.",
    )
    val seedHolderVotingAlignmentCell: Dimension = Dimension(
        prefix = "seed_holder_voting_alignment:{cell}", slug = "seed_holder_voting_alignment_cell", ccSection = "3.1.9.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("seed_holder_voting_alignment", SegmentClass.LITERAL), Segment("{cell}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Pairwise cosine of seed-holder vote vectors per voting window.",
    )
    val sessionKind: Dimension = Dimension(
        prefix = "session:{kind}", slug = "session_kind", ccSection = "3.1.3.1",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "persist", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("session", SegmentClass.LITERAL), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Which occurrence of a self is handling an addressed, stateful exchange.",
    )
    val slashingOutcome: Dimension = Dimension(
        prefix = "slashing:{outcome}", slug = "slashing_outcome", ccSection = "3.1.9.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("slashing", SegmentClass.LITERAL), Segment("{outcome}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "proven_rogue / not_proven (lowercase per CC 3.1.7 R3; the substrate's coined upheld / suspension / expertise_fraud admit as open vocab under CC 4.5.1.1).",
    )
    val system: Dimension = Dimension(
        prefix = "system:*", slug = "system_any", ccSection = "3.1.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "persist", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("system", SegmentClass.LITERAL), Segment("*", SegmentClass.WILDCARD)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val testimonialWitnessKind: Dimension = Dimension(
        prefix = "testimonial_witness:{kind}", slug = "testimonial_witness_kind", ccSection = "3.1.9.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("testimonial_witness", SegmentClass.LITERAL), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Preserves singular narrative of an affected party as singular witness — distinct from witness_diversity:* (which aggregates multiple reviewers toward consensus).",
    )
    val traceFormVersion: Dimension = Dimension(
        prefix = "trace:{form}:{version}", slug = "trace_form_version", ccSection = "3.1.5",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = true, reservedRule = "reserved (see table)",
        segments = listOf(Segment("trace", SegmentClass.LITERAL), Segment("{form}", SegmentClass.VOCAB), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "An agent's own reasoning trace carried envelope-native.",
    )
    val traceSummaryKind: Dimension = Dimension(
        prefix = "trace_summary:{kind}", slug = "trace_summary_kind", ccSection = "3.1.5",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "accord-agent", reserved = true, reservedRule = "reserved (see table)",
        segments = listOf(Segment("trace_summary", SegmentClass.LITERAL), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "Post-scrub digest of a trace for cross-node consumption when the trace itself is out of scope or over cap.",
    )
    val transparencyLogConsistency: Dimension = Dimension(
        prefix = "transparency_log:consistency", slug = "transparency_log_consistency", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("transparency_log", SegmentClass.LITERAL), Segment("consistency", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "RFC 6962 consistency proof between two STHs.",
    )
    val transparencyLogCosignedTreeSize: Dimension = Dimension(
        prefix = "transparency_log:cosigned:{tree_size}", slug = "transparency_log_cosigned_tree_size", ccSection = "3.1.2",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "attestation", reserved = true, reservedRule = "witness-emitter (identity_type contains witness)",
        segments = listOf(Segment("transparency_log", SegmentClass.LITERAL), Segment("cosigned", SegmentClass.LITERAL), Segment("{tree_size}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Witness cosignature on an STH (substrate-conformance path; the interim uses a per-region registry_sth_cosignatures table; see CC 5.3.1 endpoints).",
    )
    val transparencyLogInclusion: Dimension = Dimension(
        prefix = "transparency_log:inclusion", slug = "transparency_log_inclusion", ccSection = "3.1.2",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "attestation", reserved = false, reservedRule = null,
        segments = listOf(Segment("transparency_log", SegmentClass.LITERAL), Segment("inclusion", SegmentClass.LITERAL)),
        labelKey = null, glossKey = null,
        description = "RFC 6962 inclusion proof for an audit leaf.",
    )
    val transportKind: Dimension = Dimension(
        prefix = "transport:{kind}", slug = "transport_kind", ccSection = "3.1.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "transport-delivery", reserved = true, reservedRule = "substrate-self-report",
        segments = listOf(Segment("transport", SegmentClass.LITERAL), Segment("{kind}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "",
    )
    val trustJobVersion: Dimension = Dimension(
        prefix = "trust:{job}:{version}", slug = "trust_job_version", ccSection = "3.1.1",
        polarity = Polarity.POSITIVE_ONLY, polarityRaw = "positive-only", indeterminateAllowed = false,
        renderer = Renderer.RELATION_EDGE, owningComponent = "registry", reserved = true, reservedRule = "reserved (see table)",
        segments = listOf(Segment("trust", SegmentClass.LITERAL), Segment("{job}", SegmentClass.VOCAB), Segment("{version}", SegmentClass.VOCAB)),
        labelKey = "ceg.trust_job_version.label", glossKey = "ceg.trust_job_version.gloss",
        description = "The trust-root conferral and acceptance edges, carried as dimension values on delegates_to rows — the wire type is unchanged, so 1+4 is untouched.",
    )
    val truthGroundingSubject: Dimension = Dimension(
        prefix = "truth_grounding:{subject}", slug = "truth_grounding_subject", ccSection = "3.1.9.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("truth_grounding", SegmentClass.LITERAL), Segment("{subject}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Per-subject ground-truth signal.",
    )
    val voteContributionId: Dimension = Dimension(
        prefix = "vote:{contribution_id}", slug = "vote_contribution_id", ccSection = "3.1.9.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("vote", SegmentClass.LITERAL), Segment("{contribution_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Signed score on a Contribution (P4).",
    )
    val waAdjudicationState: Dimension = Dimension(
        prefix = "wa_adjudication:{state}", slug = "wa_adjudication_state", ccSection = "3.1.9.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.STATE_PILL, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("wa_adjudication", SegmentClass.LITERAL), Segment("{state}", SegmentClass.VOCAB)),
        labelKey = null, glossKey = null,
        description = "CC 4.3 Wise-Authority quorum adjudication finding (CIRISConstitution#73) — the attestation a wa_adjudication_ref resolves to (abandonment/seizure and successor findings).",
    )
    val watchlistId: Dimension = Dimension(
        prefix = "watchlist:{id}", slug = "watchlist_id", ccSection = "3.1.9.4",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.CONFIG_RECORD, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("watchlist", SegmentClass.LITERAL), Segment("{id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Per-group content-watchlist config.",
    )
    val weightedAggregateContributionId: Dimension = Dimension(
        prefix = "weighted_aggregate:{contribution_id}", slug = "weighted_aggregate_contribution_id", ccSection = "3.1.9.3",
        polarity = Polarity.SIGNED, polarityRaw = "signed", indeterminateAllowed = false,
        renderer = Renderer.SIGNED_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("weighted_aggregate", SegmentClass.LITERAL), Segment("{contribution_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Rolling tally per Contribution (P7).",
    )
    val witnessDiversityContributionId: Dimension = Dimension(
        prefix = "witness_diversity:{contribution_id}", slug = "witness_diversity_contribution_id", ccSection = "3.1.9.3",
        polarity = Polarity.BOOLEAN_VIA_SCORE, polarityRaw = "boolean-via-score", indeterminateAllowed = false,
        renderer = Renderer.BOOLEAN_VIA_SCORE, owningComponent = "node", reserved = false, reservedRule = null,
        segments = listOf(Segment("witness_diversity", SegmentClass.LITERAL), Segment("{contribution_id}", SegmentClass.VALUE)),
        labelKey = null, glossKey = null,
        description = "Witness set meets jurisdictional + organizational + software-stack + cell-expertise bars (P10).",
    )

    val all: List<Dimension> = listOf(
        accord,
        activityTierPeriod,
        ageAssuranceLevelBandVersion,
        ageSelfDeclaredBandVersion,
        agentFilesKindPlatformOrTarget,
        approachGoalId,
        attestationAgentIntegrity,
        attestationHardwareRooted,
        attestationLicenseValidity,
        attestationRegistryConsensus,
        attestationSelfVerify,
        auditChainHashContinuity,
        autonomyAspect,
        benchmarkHe300CategoryVersion,
        beneficenceAspect,
        bondPostedCurrency,
        buildRegisteredTarget,
        capacityComposite,
        capacityCoreIdentity,
        capacityIncompletenessAwareness,
        capacityIntegrity,
        capacityResilience,
        capacitySustainedCoherence,
        capacityAssuranceLevelDomainBandVersion,
        certValidityAuthority,
        coherenceStandingCohort,
        commitmentFulfillmentPriorContributionId,
        configScope,
        conscienceCoherence,
        conscienceEntropy,
        conscienceEpistemicHumility,
        conscienceOptimizationVeto,
        consentKind,
        contentClassClass,
        contentRatingSchemeRating,
        corpusHealthNEffMeasurable,
        creditsDomainLanguageSubstrateBuilding,
        creditsDomainLanguageSubject,
        cwClassClass,
        deliveryClass,
        deliveryReceiptStreamId,
        detectionConscienceOverrideRate,
        detectionCorrelatedActionAxis,
        detectionCrossAgentDivergence,
        detectionDistributiveAccessResourceType,
        detectionHashChainIntegrity,
        detectionIntraAgentConsistency,
        detectionTemporalDrift,
        dmaCsdma,
        dmaDsdmaDomain,
        dmaIdma,
        dmaPdma,
        dutyKind,
        expertiseDomainLanguage,
        federationDirectoryReplicationLag,
        fidelityExplainabilitySlaTier,
        fidelityAspect,
        goalScale,
        hardCaseKind,
        hardwareCustodyPlatform,
        healthLivenessVersion,
        holdsBytesSha256Prefix,
        identityContinuityRelationalAnchor,
        integrityAspect,
        judgeModelVerdictModelId,
        justiceAspect,
        keyBoundaryScope,
        licensureAuthorityId,
        localityDecisionScale,
        manifoldConformityCohort,
        meshConfigKey,
        methodApproachIdSubstrateRung,
        moderationAllegationType,
        moderationTrackRecordCommunityKeyId,
        multilateralParticipationForumKind,
        needDomainKind,
        nonMaleficenceAspect,
        objectionState,
        ownershipRelationTargetKindVersion,
        partnerRoleRole,
        peerReachabilityNetwork,
        progressMeasureMethodId,
        prohibitedCategory,
        provenanceBuildManifestTarget,
        provenanceBuildManifestTargetLocaleLangCode,
        provenanceSkillImportSource,
        provenanceSlsaLevel,
        quarantineState,
        ratchetFlagCoordinatedVotingCluster,
        ratchetFlagCounterRiiLayer,
        ratchetFlagDensityAnomaly,
        ratchetFlagExpertiseAttestationAnomaly,
        ratchetFlagHarassmentPattern,
        ratchetFlagOutOfDistributionVoting,
        reconsiderationGrounds,
        regimeArtifactVersion,
        revocationEntityTypeReason,
        rollbackDetectedRevisionField,
        seedHolderVotingAlignmentCell,
        sessionKind,
        slashingOutcome,
        system,
        testimonialWitnessKind,
        traceFormVersion,
        traceSummaryKind,
        transparencyLogConsistency,
        transparencyLogCosignedTreeSize,
        transparencyLogInclusion,
        transportKind,
        trustJobVersion,
        truthGroundingSubject,
        voteContributionId,
        waAdjudicationState,
        watchlistId,
        weightedAggregateContributionId,
        witnessDiversityContributionId,
    )

    private val byPrefixIndex: Map<String, Dimension> by lazy { all.associateBy { it.prefix } }

    /** The family whose registry prefix is exactly [prefix]. */
    fun byPrefix(prefix: String): Dimension? = byPrefixIndex[prefix]

    /**
     * The family a wire `dimension` string belongs to: the row whose literal
     * segments match the wire's leading segments, longest match wins.
     */
    fun forWire(dimension: String): Dimension? {
        val parts = dimension.split(':')
        var best: Dimension? = null
        var bestLen = -1
        for (d in all) {
            if (d.segments.size > parts.size) continue
            var ok = true
            var literals = 0
            for ((i, seg) in d.segments.withIndex()) {
                when (seg.cls) {
                    SegmentClass.LITERAL -> if (seg.segment == parts[i]) literals++ else { ok = false; break }
                    SegmentClass.WILDCARD -> {}
                    else -> if (parts[i].isEmpty()) { ok = false; break }
                }
            }
            if (ok && literals > bestLen) { best = d; bestLen = literals }
        }
        return best
    }
}

/** The CC 2.1 envelope members the receipt shows. Not registry rows; every one is glossed. */
object Envelope {
    val subjectKeyIds: EnvelopeMember = EnvelopeMember(id = "subjectKeyIds", wire = "subject_key_ids", ccSection = "2.1", labelKey = "ceg.envelope.subject_key_ids.label", glossKey = "ceg.envelope.subject_key_ids.gloss")
    val attestingKeyId: EnvelopeMember = EnvelopeMember(id = "attestingKeyId", wire = "attesting_key_id", ccSection = "2.1", labelKey = "ceg.envelope.attesting_key_id.label", glossKey = "ceg.envelope.attesting_key_id.gloss")
    val cohortScope: EnvelopeMember = EnvelopeMember(id = "cohortScope", wire = "cohort_scope", ccSection = "2.3.3", labelKey = "ceg.envelope.cohort_scope.label", glossKey = "ceg.envelope.cohort_scope.gloss")
    val dimension: EnvelopeMember = EnvelopeMember(id = "dimension", wire = "dimension", ccSection = "2.1", labelKey = "ceg.envelope.dimension.label", glossKey = "ceg.envelope.dimension.gloss")
    val consentScope: EnvelopeMember = EnvelopeMember(id = "consentScope", wire = "consent:scope", ccSection = "3.3.1", labelKey = "ceg.envelope.consent_scope.label", glossKey = "ceg.envelope.consent_scope.gloss")

    val all: List<EnvelopeMember> = listOf(subjectKeyIds, attestingKeyId, cohortScope, dimension, consentScope)
}
