//! The Z2xZ2 character sectors — the object's conserved charges.
//!
//! The automorphism group of the eleven kinds is order 4 (`Symmetry.aut_with_stack`),
//! generated by the two twin swaps [`crate::TWINS`] = (Priorities, Process) and
//! (Structure, Circumstances). Being Z2xZ2, it has four one-dimensional characters,
//! and the state space splits as a direct sum of their eigenspaces:
//!
//! ```text
//!   sector 0  (+,+)   dim 9   both twins symmetric      — the "bright" sector
//!   sector 1  (+,-)   dim 1   twin 1 antisymmetric      — the (Structure, Circumstances) dark mode
//!   sector 2  (-,+)   dim 1   twin 0 antisymmetric      — the (Priorities, Process)     dark mode
//!   sector 3  (-,-)   dim 0   both antisymmetric        — EMPTY
//! ```
//!
//! The two one-dimensional sectors ARE the dark modes: each is spanned by a single
//! [`dark_vector`]. The (-,-) sector is empty because the two swaps act on disjoint
//! index pairs, so no basis vector is odd under both — it is a real structural fact
//! about the object, not a numerical accident, and [`sector_dims`] is the place it is
//! visible.
//!
//! ## Why the sectors are the conservation law
//!
//! A coupling matrix that commutes with the group is block-diagonal across the
//! sectors: no dynamics can move amplitude between them, so sector occupancy is
//! conserved for all time. [`inter_sector_leakage`] is the diagnostic for exactly
//! that, and it is the quantity that separates the two matrices this crate ships:
//! `tables::COUPLING_SYM` is block-diagonal to machine zero, while the MEASURED
//! `data::COUPLING` is not — it leaks at ~4.51, which is a measurement about the
//! object and not an error to be cleaned up.

use crate::{tables, Mat, Vec11, N};

/// Number of Z2xZ2 character sectors.
pub const SECTORS: usize = 4;

/// `1/sqrt(2)`, the normalisation of a two-node antisymmetric mode. Taken from `core`
/// rather than computed, so no `libm` call and no rounding enters the dark vector.
const INV_SQRT2: f64 = core::f64::consts::FRAC_1_SQRT_2;

/// Dimensions of the four character sectors: `[9, 1, 1, 0]`.
///
/// They sum to [`N`] = 11 because the four characters exhaust the group.
pub fn sector_dims() -> [usize; SECTORS] {
    tables::SECTOR_DIMS
}

/// Project `v` onto character `sector` using `tables::SECTOR_PROJECTORS`.
///
/// The four projections of any vector sum back to that vector, since the projectors
/// resolve the identity.
///
/// # Panics
/// If `sector >= 4`.
pub fn project(v: &Vec11, sector: usize) -> Vec11 {
    assert!(sector < SECTORS, "sector index out of range");
    let p = &tables::SECTOR_PROJECTORS[sector];
    let mut out = [0.0f64; N];
    for i in 0..N {
        let mut acc = 0.0f64;
        for j in 0..N {
            acc += p[i][j] * v[j];
        }
        out[i] = acc;
    }
    out
}

/// The normalised dark vector of a twin pair: `d = (e_a - e_b)/sqrt(2)` for
/// `(a, b) = crate::TWINS[twin]`.
///
/// This is `DarkState.dark` up to normalisation. Under a coupling that is symmetric
/// in the pair it is an exact eigenvector with eigenvalue `-c_ab`
/// (`DarkState.twin_dark_state`), and every other row annihilates it
/// (`DarkState.dark_state_decoupled`) — which is what [`crate::twin_probe::probe`]
/// exercises.
///
/// The sign convention is `+` on the first member of the pair. Both signs span the
/// same sector, so the choice is cosmetic; it is fixed here so results replay
/// bit-identically.
///
/// # Panics
/// If `twin >= 2`.
pub fn dark_vector(twin: usize) -> Vec11 {
    assert!(twin < crate::TWINS.len(), "twin index out of range");
    let (a, b) = crate::TWINS[twin];
    let mut d = [0.0f64; N];
    d[a] = INV_SQRT2;
    d[b] = -INV_SQRT2;
    d
}

/// Matrix product, fixed loop order so the float accumulation is deterministic.
fn mul(a: &Mat, b: &Mat) -> Mat {
    let mut out = [[0.0f64; N]; N];
    for i in 0..N {
        for j in 0..N {
            let mut acc = 0.0f64;
            for k in 0..N {
                acc += a[i][k] * b[k][j];
            }
            out[i][j] = acc;
        }
    }
    out
}

/// The conservation diagnostic: `max |P_a M P_b|` over all entries and all ordered
/// sector pairs `a != b`.
///
/// Zero means `M` commutes with the twin group, so sector occupancy is conserved
/// exactly and each dark mode evolves on its own forever. Nonzero is the rate at
/// which the sectors talk to each other.
///
/// Measured on the two matrices this crate ships:
///
/// ```text
///   tables::COUPLING_SYM   0        (block-diagonal by construction)
///   data::COUPLING         4.508…   (entry [2][6] of the (+,+)-(+,-) block:
///                                    Manner couples to Structure at 9.016 and to
///                                    Circumstances at 0 — that whole asymmetry
///                                    lands in the dark sector)
/// ```
pub fn inter_sector_leakage(m: &Mat) -> f64 {
    let mut worst = 0.0f64;
    for a in 0..SECTORS {
        let pm = mul(&tables::SECTOR_PROJECTORS[a], m);
        for b in 0..SECTORS {
            if a == b {
                continue;
            }
            let block = mul(&pm, &tables::SECTOR_PROJECTORS[b]);
            for i in 0..N {
                for j in 0..N {
                    let v = libm::fabs(block[i][j]);
                    if v > worst {
                        worst = v;
                    }
                }
            }
        }
    }
    worst
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::COUPLING;
    use crate::tables::COUPLING_SYM;

    #[test]
    fn sector_dims_are_nine_one_one_zero() {
        assert_eq!(sector_dims(), [9, 1, 1, 0]);
        assert_eq!(sector_dims().iter().sum::<usize>(), N);
    }

    /// The dimensions are the projector traces, so the table cannot disagree with
    /// itself without this failing.
    #[test]
    fn sector_dims_are_the_projector_traces() {
        for s in 0..SECTORS {
            let mut tr = 0.0f64;
            for i in 0..N {
                tr += tables::SECTOR_PROJECTORS[s][i][i];
            }
            assert!(
                libm::fabs(tr - sector_dims()[s] as f64) < 1e-12,
                "sector {s}: trace {tr} != dim {}",
                sector_dims()[s]
            );
        }
    }

    /// The four projectors resolve the identity: every vector is the sum of its
    /// four sector components.
    #[test]
    fn projectors_resolve_the_identity() {
        let v: Vec11 = [1.0, -2.0, 3.5, 0.25, -7.0, 11.0, 0.5, -0.5, 2.0, -3.0, 13.0];
        let mut sum = [0.0f64; N];
        for s in 0..SECTORS {
            let p = project(&v, s);
            for i in 0..N {
                sum[i] += p[i];
            }
        }
        for i in 0..N {
            assert!(libm::fabs(sum[i] - v[i]) < 1e-12, "component {i}");
        }
    }

    /// Each dark vector is a unit vector living entirely inside its own
    /// one-dimensional sector: twin 0 in sector 2 (-,+), twin 1 in sector 1 (+,-).
    #[test]
    fn dark_vectors_span_the_one_dimensional_sectors() {
        for (twin, own) in [(0usize, 2usize), (1, 1)] {
            let d = dark_vector(twin);
            let norm_sq: f64 = d.iter().map(|x| x * x).sum();
            assert!(libm::fabs(norm_sq - 1.0) < 1e-15, "twin {twin} not normalised");
            for s in 0..SECTORS {
                let p = project(&d, s);
                let residual: f64 = if s == own {
                    (0..N).map(|i| libm::fabs(p[i] - d[i])).fold(0.0, f64::max)
                } else {
                    (0..N).map(|i| libm::fabs(p[i])).fold(0.0, f64::max)
                };
                assert!(residual < 1e-15, "twin {twin} sector {s}: residual {residual}");
            }
        }
    }

    #[test]
    fn symmetrised_coupling_conserves_the_sectors() {
        let leak = inter_sector_leakage(&COUPLING_SYM);
        assert!(leak < 1e-12, "COUPLING_SYM leaked {leak}, expected machine zero");
    }

    /// The measured coupling does NOT conserve them, and the size of the violation
    /// is a measurement — CIRISOntology reads it at ~4.51.
    #[test]
    fn measured_coupling_leaks_across_sectors() {
        let leak = inter_sector_leakage(&COUPLING);
        assert!(leak > 1.0, "COUPLING leaked only {leak}, expected ~4.51");
        assert!(
            libm::fabs(leak - 4.508_157_515_13) < 1e-9,
            "COUPLING leakage {leak}, expected 4.508157515"
        );
    }
}
