import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("com.android.library")
    id("org.jetbrains.compose")
    kotlin("plugin.compose")
}

// yubikit-android 3.1.0 transitively requests kotlin-stdlib 2.2.10 (metadata 2.2.0),
// which the project's Kotlin 2.0.21 compiler can't read (it crashes the FIR checker).
// Pin stdlib to the compiler's own version — the API yubikit uses is unchanged; only
// the .kotlin_module metadata version differs.
configurations.all {
    resolutionStrategy {
        force(
            "org.jetbrains.kotlin:kotlin-stdlib:2.0.21",
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.21",
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.0.21",
        )
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// BUILD FLAVOR — the drift that used to be a fork (client/VENDORING.md §4)
//
// The client version is GENERATED, not hand-edited. It was a `const val` in
// commonMain, kept in step with the substrate by a script in one consuming repo
// and by nothing at all in the other, where it drifted far enough to show every
// user a mismatch banner against the node their own app shipped with. It now
// comes from the repo-root VERSION file — the same file the published wheel
// takes its version from, so `ciris-client==X` and `ciris-server==X` are the
// pair and the banner cannot disagree with the package that shipped it.
//
// THERE IS NO BUILD FLAVOR ANY MORE. This block used to generate
// `CIRISBuild.HAS_AGENT` too, and the module shipped in a node and an agent
// variant. CIRISServer#479 deleted that constant: an agent IS a node that has
// had a brain added, so "are the agent surfaces live?" is a question about the
// ATTACHED NODE and is answered by the probed ClientMode at runtime. One
// artifact ships and narrows itself. CIRISBuild.kt is a committed tombstone
// explaining the same thing.
//
// CACHE NOTE (CIRISServer#272). CLIENT_VERSION's KDoc warns that mutating it at
// build time recompiled the whole Compose client and defeated the desktop-JAR
// gradle cache "every leg". Generation does not reintroduce that: the generated
// text is a pure function of the version, so it is byte-stable across builds of
// the same version and the cache holds. #272's cost was a value that differed
// per CI leg.
// ─────────────────────────────────────────────────────────────────────────────


// The single source of the client version: the repo-root VERSION file, which is
// also where the Python package version comes from. No default — a build that
// cannot find it must say so rather than stamp a plausible wrong number into
// the version-mismatch banner every user sees.
val clientVersion: String = (project.findProperty("clientVersion") as String?)
    ?: rootProject.projectDir.parentFile.resolve("VERSION")
        .takeIf { it.isFile }
        ?.readText()
        ?.trim()
        ?.takeIf { it.isNotEmpty() }
    ?: throw GradleException(
        "No client version. Pass -PclientVersion=<v>, or provide a non-empty " +
            "VERSION file at ${rootProject.projectDir.parentFile.resolve("VERSION")}."
    )

val generatedFlavorDir: Provider<Directory> =
    layout.buildDirectory.dir("generated/flavor/commonMain/kotlin")

val generateBuildFlavor by tasks.registering {
    description = "Generate CLIENT_VERSION from the repo-root VERSION file"
    group = "build"

    // Declared as an input so a version change re-runs the task and nothing
    // else does.
    inputs.property("clientVersion", clientVersion)
    outputs.dir(generatedFlavorDir)

    doLast {
        val root = generatedFlavorDir.get().asFile
        val pkg = File(root, "ai/ciris/mobile/shared").apply { mkdirs() }
        val modelsPkg = File(pkg, "models").apply { mkdirs() }

        File(modelsPkg, "ClientVersion.kt").writeText(
            """
            // GENERATED by :shared:generateBuildFlavor — do not edit, do not commit.
            package ai.ciris.mobile.shared.models

            /**
             * The client build version, used for the node-vs-client VERSION-MISMATCH
             * banner.
             *
             * Generated from the repo-root VERSION file — the same file the published
             * `ciris-client` wheel takes its version from. So `ciris-client==X` and
             * `ciris-server==X` are the pair, and the banner cannot disagree with the
             * package that shipped it.
             *
             * It used to be a hand-edited `const val` here, kept in step with the
             * substrate by a script in one consuming repo and by nothing at all in the
             * other, where it drifted far enough to show every user a mismatch banner
             * against the node their own app shipped with.
             */
            const val CLIENT_VERSION: String = "$clientVersion"
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    // Suppress expect/actual beta warnings - feature is stable enough for production use
    targets.all {
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions {
                    freeCompilerArgs.add("-Xexpect-actual-classes")
                }
            }
        }
    }

    // Android
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    // iOS
    //
    // The per-target frameworks are declared into an XCFramework so there is a
    // single artifact to ship. Without the XCFramework DSL the build only
    // produces `linkReleaseFrameworkIosArm64` and friends — three separate
    // frameworks that no consumer can depend on as one, and no
    // `assemble*XCFramework` task at all (client/CLAUDE.md documented one that
    // has never existed). Device and simulator slices cannot live in a fat
    // framework because both carry arm64; an XCFramework is the packaging that
    // holds them together.
    val xcf = XCFramework("shared")
    listOf(
        // iosX64 — the INTEL simulator — is deliberately absent.
        //
        // The XCFramework is three sequential release links and nothing else:
        // iosArm64 81m, iosSimulatorArm64 80m, iosX64 83m, measured on the
        // 0.5.189 publish. Release linking is whole-program LLVM optimisation
        // over all of Compose Multiplatform, Kotlin/Native does not use
        // compiler caches for optimised binaries, and Gradle parallelism does
        // not apply because all three tasks live in this one project. So the
        // only lever on a four-hour build is how many of those links exist.
        //
        // What iosX64 buys is running the SIMULATOR on an Intel Mac. The device
        // target and the Apple Silicon simulator are untouched, CI runs on
        // macos-14 (ARM), and no shipped artifact loses a platform: an iPhone
        // build uses iosArm64 either way.
        //
        // PUTTING IT BACK is one line and 83 minutes per release. Do that the
        // moment someone actually needs an Intel simulator — this is a cost
        // decision, not a claim that Intel Macs do not exist.
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "shared"
            isStatic = true
            xcf.add(this)
        }
    }

    // Desktop (JVM)
    jvm("desktop") {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    // Web (WASM).
    //
    // The warning that stood here said production builds fail at runtime on
    // KT-69154 ("kotlin.wasm.internal.throwJsError: function import requires a
    // callable") and that only developmentExecutable should ever ship. That was
    // RETESTED on Kotlin 2.0.21 and is no longer true: the production bundle
    // was served and loaded in a browser, instantiated, rendered the startup
    // sequence, and ran real client code (CIRISApiClient probes, the
    // localization loader, a typed NodeRefusal) with no LinkError. The reported
    // symptom is commonly a STALE dist directory rather than a compiler defect,
    // which is why a clean build clears it.
    //
    // It matters because the two differ by more than a flag: the development
    // bundle is 69 MB and the production bundle is 28 MB. A web interface is
    // downloaded by every visitor, so shipping the development build would put
    // 41 MB of unminified payload on the wire for no reason.
    //
    // Ship `wasmJsBrowserDistribution` (production). If a LinkError ever
    // reappears, clean `shared/build/dist/wasmJs` and rebuild BEFORE concluding
    // the compiler broke.
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        moduleName = "ciris-shared"
        browser {
            commonWebpackConfig {
                outputFileName = "ciris-shared.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        val commonMain by getting {
            // CLIENT_VERSION, generated from the repo-root VERSION file.
            kotlin.srcDir(generateBuildFlavor)

            dependencies {
                // Compose Multiplatform
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                // implementation(compose.materialIconsExtended) // 113MB — replaced by ui/icons/CIRISMaterialIcons.kt
                // Extended icons defined inline in ui/icons/CIRISMaterialIcons.kt (~93KB)
                // To add a new icon: copy SVG path from fonts.google.com/icons into CIRISMaterialIcons.kt
                //   then add an extension property in MaterialIconCompat.kt
                implementation(compose.components.resources)
                @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
                implementation(compose.components.uiToolingPreview)

                // Coroutines
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")

                // Serialization
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")

                // Date/Time
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.1")

                // Ktor client
                implementation("io.ktor:ktor-client-core:3.0.3")
                implementation("io.ktor:ktor-client-content-negotiation:3.0.3")
                implementation("io.ktor:ktor-serialization-kotlinx-json:3.0.3")
                implementation("io.ktor:ktor-client-logging:3.0.3")
                implementation("io.ktor:ktor-client-auth:3.0.3")

                // Multiplatform ViewModel
                implementation("org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose:2.8.4")
                implementation("org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose:2.8.4")

                // Navigation
                implementation("org.jetbrains.androidx.navigation:navigation-compose:2.8.0-alpha10")

                // Generated API client
                implementation(project(":generated-api"))
            }
        }

        val androidMain by getting {
            dependencies {
                // Ktor Android engine
                implementation("io.ktor:ktor-client-okhttp:3.0.3")

                // Ktor server for local LLM HTTP API and test automation
                implementation("io.ktor:ktor-server-core:3.0.3")
                implementation("io.ktor:ktor-server-cio:3.0.3")
                implementation("io.ktor:ktor-server-content-negotiation:3.0.3")
                implementation("io.ktor:ktor-server-status-pages:3.0.3")

                // On-device LLM inference via ONNX Runtime
                // 64-bit devices (arm64-v8a, x86_64): Full on-device inference
                // 32-bit devices (armeabi-v7a): Falls back to "Local Inference Server" provider
                // 16 KB page-size alignment story:
                //   1.17.0 — both libonnxruntime + libonnxruntime4j_jni 4 KB aligned (rejected by Play)
                //   1.21.0 — libonnxruntime 16 KB ✅, but libonnxruntime4j_jni still 4 KB ❌
                //   1.25.0 — both 16 KB aligned ✅
                // 1.25.0 is the current stable; pinning here so a downgrade
                // doesn't silently re-introduce the Play rejection.
                implementation("com.microsoft.onnxruntime:onnxruntime-android:1.25.0")

                // Android-specific
                implementation("androidx.core:core-ktx:1.12.0")
                implementation("androidx.security:security-crypto:1.1.0-alpha06")
                implementation("androidx.activity:activity-compose:1.9.3")

                // Google Play Services
                // On-device YubiKey PIV over NFC (YubiKey-backed fed-ID). Ed25519
                // slot-9c signing needs firmware 5.7+ and yubikit >= 2.6.
                implementation("com.yubico.yubikit:android:3.1.0")
                implementation("com.yubico.yubikit:piv:3.1.0")
                implementation("com.yubico.yubikit:core:3.1.0")

                implementation("com.google.android.gms:play-services-auth:20.7.0")
                implementation("com.android.billingclient:billing-ktx:7.1.1")
                implementation("com.google.android.play:integrity:1.4.0")

                // Chrome Custom Tabs
                implementation("androidx.browser:browser:1.7.0")

                // Image loading
                implementation("io.coil-kt:coil-compose:2.5.0")

                // WorkManager for background task scheduling
                implementation("androidx.work:work-runtime-ktx:2.9.0")
            }
        }

        val iosMain by creating {
            dependsOn(commonMain)
            dependencies {
                implementation("io.ktor:ktor-client-darwin:3.0.3")
            }
        }

        val iosArm64Main by getting { dependsOn(iosMain) }
        val iosSimulatorArm64Main by getting { dependsOn(iosMain) }

        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation("io.ktor:ktor-client-cio:3.0.3")
                // NOTE: federation crypto (JCS canonicalization + hybrid signing)
                // is performed entirely by THIS device's local ciris-server node in
                // its substrate. The app drives the node over localhost HTTP and
                // holds NO federation keys, so there is no BouncyCastle / ML-DSA
                // dependency here anymore.
            }
        }

        val wasmJsMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-js:3.0.3")
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
            }
        }

        val desktopTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
            }
        }
    }
}

android {
    namespace = "ai.ciris.mobile.shared"
    compileSdk = 36

    defaultConfig {
        minSdk = 24
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// THE PUBLISHED AAR MUST CARRY :generated-api's CLASSES.
//
// An Android AAR never contains its project dependencies' classes. Gradle
// expects a consumer to resolve them from a repository using the POM or module
// metadata that sits beside the artifact.
//
// This AAR has neither. It is published as a bare file on a GitHub release and
// dropped into `apps/android/libs/`, so there is no repository to resolve
// anything from — which made `implementation(project(":generated-api"))`
// structurally unable to reach a consumer. The result shipped: 0.5.195's AAR
// holds 5,820 `ai/ciris/mobile` classes and zero `ai/ciris/api`, and every APK
// built against it died in onCreate with
//
//     NoClassDefFoundError: Lai/ciris/api/apis/AgentApi;
//     at CIRISApiClient.<init>(CIRISApiClient.kt:446)
//
// on the app's startup path (CIRISClient#25).
//
// So the AAR is fat: the two class sets are merged into one classes.jar. That
// matches how it is actually consumed — a file, not a coordinate.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build the fat AAR and refuse to emit one that would crash on launch.
 *
 * Done with explicit zip surgery rather than Gradle file-collection wiring: the
 * lazy `from {}` forms resolve at configuration time and cannot see an AAR that
 * does not exist yet. This is longer and it is deterministic.
 */
val fatReleaseAar by tasks.registering {
    dependsOn("bundleReleaseAar", ":generated-api:bundleReleaseAar")

    val sharedAar = layout.buildDirectory.file("outputs/aar/shared-release.aar")
    val genAar = project(":generated-api").layout.buildDirectory
        .file("outputs/aar/generated-api-release.aar")
    val outAar = layout.buildDirectory.file("fataar/shared-release-fat.aar")

    inputs.file(sharedAar)
    inputs.file(genAar)
    outputs.file(outAar)

    doLast {
        val src = sharedAar.get().asFile
        val gen = genAar.get().asFile
        val dst = outAar.get().asFile
        dst.parentFile.mkdirs()

        fun classesOf(aar: File): Map<String, ByteArray> {
            val out = LinkedHashMap<String, ByteArray>()
            ZipFile(aar).use { z ->
                val entry = z.getEntry("classes.jar")
                    ?: error("no classes.jar inside ${aar.name}")
                val jarBytes = z.getInputStream(entry).readBytes()
                val tmp = File.createTempFile("classes", ".jar")
                tmp.writeBytes(jarBytes)
                ZipFile(tmp).use { j ->
                    for (e in j.entries()) {
                        if (e.isDirectory) continue
                        if (e.name.startsWith("META-INF/") &&
                            (e.name.endsWith(".SF") || e.name.endsWith(".DSA") || e.name.endsWith(".RSA"))
                        ) continue
                        out[e.name] = j.getInputStream(e).readBytes()
                    }
                }
                tmp.delete()
            }
            return out
        }

        // :shared first, then :generated-api. On the (unexpected) case of a
        // name collision, :shared wins and we say so rather than silently
        // preferring whichever was iterated last.
        val merged = LinkedHashMap<String, ByteArray>()
        merged.putAll(classesOf(src))
        var collisions = 0
        for ((name, bytes) in classesOf(gen)) {
            if (merged.putIfAbsent(name, bytes) != null) collisions++
        }
        if (collisions > 0) {
            logger.lifecycle("[fat-aar] $collisions duplicate entry(ies); :shared kept")
        }

        val mobile = merged.keys.count { it.startsWith("ai/ciris/mobile/") && it.endsWith(".class") }
        val api = merged.keys.count { it.startsWith("ai/ciris/api/") && it.endsWith(".class") }
        logger.lifecycle("[fat-aar] ai/ciris/mobile: $mobile   ai/ciris/api: $api")

        // The gate. 0.5.195 published a 16 MB AAR from a BUILD SUCCESSFUL with
        // zero ai/ciris/api classes in it, so "the build worked" establishes
        // nothing here. Assert the class the crash actually named.
        if (mobile == 0) error("fat AAR lost :shared entirely")
        if (api == 0) error(
            "fat AAR carries no ai/ciris/api classes — every APK built against it " +
            "dies in onCreate (CIRISClient#25)"
        )
        if (!merged.containsKey("ai/ciris/api/apis/AgentApi.class")) error(
            "ai/ciris/api/apis/AgentApi is absent — the exact class NoClassDefFoundError named"
        )

        // classes.jar, then the rest of :shared's AAR around it.
        val mergedJar = File(dst.parentFile, "classes.jar")
        ZipOutputStream(mergedJar.outputStream().buffered()).use { out ->
            for ((name, bytes) in merged) {
                out.putNextEntry(ZipEntry(name))
                out.write(bytes)
                out.closeEntry()
            }
        }
        ZipOutputStream(dst.outputStream().buffered()).use { out ->
            ZipFile(src).use { z ->
                for (e in z.entries()) {
                    if (e.isDirectory || e.name == "classes.jar") continue
                    out.putNextEntry(ZipEntry(e.name))
                    out.write(z.getInputStream(e).readBytes())
                    out.closeEntry()
                }
            }
            out.putNextEntry(ZipEntry("classes.jar"))
            out.write(mergedJar.readBytes())
            out.closeEntry()
        }
        mergedJar.delete()
        logger.lifecycle("[fat-aar] wrote ${dst.name} (${dst.length()} bytes)")
    }
}
